# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNTreasureDataExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../node_modules/react-native'
  pod 'RNTreasureData', :path => '../node_modules/react-native-td'

  target 'RNTreasureDataExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'RNTreasureDataExample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNTreasureDataExample-tvOS

  target 'RNTreasureDataExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
